# Generated by Django 3.0.6 on 2020-05-31 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('finish_date', models.DateField(null=True)),
                ('costumers', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='task_register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_reg', models.DateTimeField()),
                ('time_task', models.IntegerField()),
                ('description', models.TextField(max_length=300)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project', to='core.Project')),
            ],
        ),
    ]
