# Generated by Django 3.0.6 on 2020-05-31 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_task_register_short_descriptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='task_register',
            name='status',
            field=models.CharField(blank=True, choices=[('wg', 'Aguardando'), ('eg', 'Em Execução'), ('dn', 'Concluído')], max_length=2),
        ),
        migrations.AlterField(
            model_name='task_register',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='task_register',
            name='short_descriptions',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
