# Generated by Django 3.0.6 on 2020-05-31 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200531_0119'),
    ]

    operations = [
        migrations.AddField(
            model_name='task_register',
            name='critical_points',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
