# Generated by Django 3.0.6 on 2020-05-31 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_task_register_critical_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task_register',
            name='critical_points',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
