# Generated by Django 3.0.6 on 2020-05-31 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200531_0142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task_register',
            name='time_task',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
