# Generated by Django 3.0.6 on 2020-05-31 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200531_0148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task_register',
            name='status',
            field=models.CharField(blank=True, choices=[('wg', 'Aguardando'), ('eg', 'Em Execução'), ('dn', 'Concluído')], default='Aguardando', max_length=2),
        ),
    ]
