# Generated by Django 3.0.6 on 2020-05-31 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20200531_0149'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='task_register',
            new_name='Task',
        ),
    ]
