# Generated by Django 3.0.6 on 2020-06-04 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_taskdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskdetails',
            name='task_details_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='taskdetails',
            name='task_details_time',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
