# Generated by Django 3.0.6 on 2020-06-08 03:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20200604_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskdetails',
            name='id_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task', to='core.Task'),
        ),
    ]
